### ISSUE TITLE
Add "else" option to probability inclusions

### ISSUE THREAD

**Issue by dmmaus** [dmmaus/mezzacotta-generator#1]
Example of the problem:

`with 3$number thousand meeples`

30% of the time generates "with two thousand meeples" (or three thousand, etc). But 70% of the time it generates "with thousand meeples".

Idea: Specify an "else" option:

`with 3$number|a thousand meeples`

30% of the time generates "with two thousand meeples" (or three thousand, etc). 70% of the time it generates "with a thousand meeples".

The pipe character might be tricky since it already has a meaning to the parser. If we can use it that would be great, but we can use another character instead.

**Comment by voidstaroz** [comment]
Can't be | to designate the alternate text. Using / instead.

**Comment by voidstaroz** [comment]
Actually can't be / either, using >
